# Generated by Django 4.1.3 on 2022-11-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='nimi',
            field=models.CharField(default='', max_length=20),
        ),
    ]
