# Generated by Django 4.1.3 on 2022-11-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='gamer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
