# Generated by Django 4.1.3 on 2022-12-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_boardgame_boardgamer_boardgame_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='edit_date',
            field=models.DateTimeField(default='Null'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='loan_date',
            field=models.DateTimeField(default='Null'),
        ),
    ]
