# Generated by Django 4.1.3 on 2022-11-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_boardgame_nimi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=20)),
                ('varaukset', models.IntegerField()),
            ],
        ),
    ]
