# Generated by Django 4.1.3 on 2022-11-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0003_user_info_gamer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Info',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='boardgamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_games.boardgamer'),
        ),
    ]
