# Generated by Django 4.1.3 on 2022-11-30 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0004_delete_user_info_boardgame_boardgamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
