# Generated by Django 4.1.1 on 2022-11-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0003_boardgamer'),
        ('board_games', '0004_delete_user_info_boardgame_boardgamer'),
    ]

    operations = [
    ]
