# Generated by Django 4.1.3 on 2022-12-05 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0004_boardgame_owner_alter_boardgame_edit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='board_games.boardgamer'),
        ),
    ]
