# Generated by Django 4.1.3 on 2022-11-30 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0005_boardgame_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgame',
            name='loan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
