# Generated by Django 4.1.3 on 2022-12-06 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=20, unique=True)),
                ('varaukset', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('salasana', models.CharField(max_length=20)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='board_games.boardgamer')),
            ],
        ),
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=20)),
                ('selitys', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loan_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
                ('boardgamer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_games.boardgamer')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='board_games.boardgamer')),
            ],
        ),
    ]
