# Generated by Django 4.1.3 on 2022-12-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_alter_boardgamer_nimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamer',
            name='bio',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='boardgamer',
            name='puh',
            field=models.IntegerField(default='Null'),
        ),
    ]
