# Generated by Django 4.1.3 on 2022-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0004_alter_boardgamer_puh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamer',
            name='bio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='boardgamer',
            name='puh',
            field=models.IntegerField(blank=True),
        ),
    ]
