# Generated by Django 4.1.3 on 2022-12-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0006_alter_boardgamer_puh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamer',
            name='puh',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
